version: '3.7'
services:
  gitea:
    image: gitea_local:latest
    container_name: gitea_openshift
    volumes:
      - /tmp/gitea/repos:/gitea-repositories
    ports:
      - "3000:3000"
      - "22:22"
    depends_on:
      - db
    restart: always
  db:
    image: postgres:9.5
    restart: always
    container_name: gitea_pg
    environment:
      - POSTGRES_USER=gitea
      - POSTGRES_PASSWORD=gitea
      - POSTGRES_DB=gitea
      # - POSTGRESQL_ADMIN_PASSWORD=gitea
    volumes:
      - /tmp/gitea/db/:/var/lib/postgresql/data
    ports:
      - "5432:5432"